pub const NOUNS: &[&str] = &[
    "ant", "ape", "ash", "asp", "bat", "bee", "boa", "bug", "car", "cat", "cod", "cow", "dog",
    "eel", "elk", "elm", "emu", "fir", "fly", "fox", "git", "hat", "jay", "koi", "oak", "owl",
    "pig", "rat", "tie", "yak", "bass", "bear", "belt", "bike", "bird", "boar", "boat", "carp",
    "clam", "club", "coat", "crab", "crow", "deer", "dove", "duck", "fish", "flea", "fowl", "frog",
    "goat", "guan", "gull", "hare", "hawk", "iris", "kelp", "king", "kite", "kiwi", "lark", "lily",
    "line", "lion", "loon", "lynx", "mink", "mite", "mole", "moth", "mule", "newt", "orca", "oval",
    "path", "pawn", "pike", "pine", "pony", "puma", "punk", "rook", "rose", "sage", "ship", "shoe",
    "slug", "sock", "sole", "star", "swan", "tahr", "tern", "tick", "toad", "tuna", "vole", "wasp",
    "wolf", "worm", "wren", "alder", "angle", "aphid", "apple", "aspen", "aster", "beech", "birch",
    "bison", "bovid", "camel", "canid", "cedar", "cobra", "coral", "crane", "curve", "daisy",
    "dingo", "dress", "dwarf", "dweeb", "eagle", "egret", "finch", "gayal", "gecko", "ghost",
    "ghoul", "glove", "golem", "goose", "guppy", "heart", "heron", "hiker", "holly", "horse",
    "hyena", "jeans", "koala", "krill", "larch", "leech", "lemur", "lilac", "llama", "louse",
    "macaw", "maple", "moose", "mouse", "ninja", "otter", "panda", "pants", "perch", "plane",
    "point", "poppy", "prawn", "quail", "queen", "raven", "scarf", "shark", "sheep", "shirt",
    "shrew", "skink", "skirt", "skunk", "sloth", "smelt", "snail", "snake", "snipe", "spade",
    "squid", "stoat", "stork", "swift", "tiger", "track", "train", "troll", "trout", "truck",
    "tulip", "viper", "whale", "wheel", "witch", "zebra", "alpaca", "azalea", "baboon", "badger",
    "beaver", "bedbug", "beetle", "bishop", "bobcat", "bonobo", "cattle", "cherry", "cicada",
    "circle", "clover", "condor", "cougar", "coyote", "crocus", "cuckoo", "dahlia", "dancer",
    "donkey", "dragon", "earwig", "ermine", "falcon", "ferret", "gerbil", "gibbon", "goblin",
    "gopher", "grouse", "hornet", "iguana", "impala", "jackal", "jaguar", "jogger", "knight",
    "leopon", "lifter", "limpet", "lizard", "locust", "magpie", "mammal", "marlin", "marmot",
    "marten", "minnow", "monkey", "muskox", "ocelot", "orchid", "parrot", "pigeon", "pirate",
    "possum", "puffin", "python", "quokka", "rabbit", "rodent", "runner", "salmon", "shrimp",
    "skater", "skiier", "skrewt", "spider", "spruce", "square", "thrush", "toucan", "turkey",
    "turtle", "viking", "violet", "walker", "walnut", "walrus", "weasel", "willow", "wizard",
    "wombat", "wraith", "begonia", "buckeye", "buffalo", "buzzard", "canidae", "caribou",
    "centaur", "cheetah", "chicken", "climber", "crawdad", "cricket", "cypress", "diamond",
    "dogwood", "dolphin", "echidna", "felidae", "firefly", "gazelle", "giraffe", "gorilla",
    "griffin", "guanaco", "gymnast", "haddock", "halibut", "hamster", "harrier", "herring",
    "hexagon", "hickory", "juniper", "ladybug", "lamprey", "lemming", "leopard", "lobster",
    "manatee", "meerkat", "mollusk", "monster", "narwhal", "niffler", "octagon", "octopus",
    "opossum", "ostrich", "panther", "peacock", "peafowl", "pelican", "penguin", "phoenix",
    "piranha", "primate", "raccoon", "reptile", "rooster", "samurai", "scallop", "sparrow",
    "swallow", "swimmer", "termite", "tribble", "unicorn", "vulture", "wallaby", "warbler",
    "warlock", "whippet", "wildcat",
];
